config/routes.rb
Rails.application.routes.draw do
  resources :jobs
  root 'jobs#index'
end

app/models/job.rb
class Job < ActiveRecord::Base
	validates :title, presence: true
	validates :company, presence: true
    validates :url, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
  	@jobs = Job.page(params[:page]).per(3)
  end

  def new
	@job = Job.new
  end

  def create
  	@job = Job.new(params.require(:job).permit(:title, :company, :url))
  	if @job.save
  	  redirect_to root_path
 	else
  	  render "new"
 	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/index.html.erb
<div class="panel panel-primary">
  <div class="panel-heading ">
    <center>
      <h1><b>Jobs Board</b></h1>
    </center>
  </div>
</div>

<p><%= link_to "+ Add Job", new_job_path, class: "btn btn-success" %></p>

<center>
  <p><%= paginate @jobs %></p>
</center>

<% @jobs.each_with_index do |job, index| %>
	<div class="panel panel-primary">
		<div class="panel-heading ">
			<h4><%= index+1 %>. <b><%= job.title %></b></h4>
		</div>
		<div class="panel-body">
			<table>
				<tr>
					<td><b>Company: </b></td>
					<td>&nbsp <%= job.company %></td>
				</tr>
				<tr>
					<td><b>Job link: </b></td>
					<td>&nbsp <%= link_to job.url, job.url %></td>
				</tr>
			</table>
		</div>
	</div>
<% end %>

<center>
  <p><%= paginate @jobs %></p>
</center>

app/views/jobs/new.html.erb
<div class="panel panel-success">
  <div class="panel-heading">
  	<center>
  		<h2>New Job</h2>
  	</center>
  </div>

  <div class="panel-body">
  	<%= simple_form_for @job , html: { class: "form-horizontal"} do |form| %>
	  	<div class="form-group">
	  		<%= form.input :title, label: "Job title" %>
	  	</div>
	  	<div class="form-group">
	  		<%= form.input :company, label: "Your company" %>
	  	</div>
	  	<div class="form-group">
	 		<%= form.input :url, label: "Link to job" %>
	  	</div>
	  	<hr/>
	  	<center>
	  		<%= form.button :submit , class: "btn btn-success"%>
	  	</center>
	<% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JobsboardApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<header class="navbar navbar-fixed-top">
	<div class="container">
		<%= link_to image_tag("Job-Board.png", alt: "Job Board Logo", size: "100x50"), 'https://medium.com/@riklomas/how-to-create-a-simple-jobs-board-in-ruby-on-rails-ev		en-if-youve-never-coded-before-9b296c4df483#.eswsj7ny2', id: 'job-board-logo' %>
		<nav>
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to "Home",root_path %></li>
				<li><%= link_to "New",new_job_path %></li>
			</ul>
		</nav>
	</div>
</header>

<%= yield %>

<footer class="footer">
	Based on the website found 
	<a href="https://medium.com/@riklomas/how-to-create-a-simple-jobs-board-in-ruby-on-rails-ev			en-if-youve-never-coded-before-9b296c4df483#.eswsj7ny2">here</a>.
</footer>

</body>
</html>